### ISSUE TITLE
dropbox for the next newsletter

### ISSUE THREAD

**Issue by daviddias** [ipfs/roundups#46] opened 2016-06-05 19:55 UTC
Thought of opening a issue to drop links + updates of thinks as they happen, so that they can be added to the next newsletter (text might be a bit raw, but they are pointers so that we don't forget)
- https://github.com/ipfs/js-ipfs-api/releases/tag/v5.0.0

**Comment by RichardLitt** [comment] 2016-06-12 13:28
Duplicate of https://github.com/ipfs/newsletter/issues/43?

**Closed as completed** 2016-06-12 13:28 UTC
